### ISSUE TITLE
what is the difference between open-lambda/s19-lambda and open-lambda/open-lambda

### ISSUE THREAD

**Issue by ZikeWang** [open-lambda/s19-lambda#8]
As I can see, s19-lambda's README file is more detailed than open-lambda's. What is the difference between these two projects? Why not update directly in open-lambda/open-lambda? 
Additionally, could you please provides with more documents about the deployment, architecture and implementation. They are useful to newcomers but still poor.

**Comment by tylerharter** [comment]
s19 is for Spring 19, and it's a space for some students working on OL to do their semester work.

You should start here: https://github.com/open-lambda/open-lambda.  I've been streamlining this a lot lately.

Instead of giving setup instructions, we now link to the setup scripts we use to build the VM that does nightly builds/tests: https://github.com/open-lambda/testing/blob/master/dev-build/bootstrap2.sh.  The thought is that if you setup a similar environment, you can be sure you're using an env that has passed our tests.

**Comment by ZikeWang** [comment]
Thanks a lot！
